# -*- coding: utf-8 -*-
"""App_Movie_Rec_Sysd2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XdH_So2CTzdRHKZ2WBr0wxSipVoraH9E
"""

from flask import Flask, jsonify
from flask_cors import CORS
import pickle

CORS(app, origins=[
    "https://movie-recommender-system-vert.vercel.app"
])

app = Flask(__name__)

@app.route("/")
def home():
    return "Welcome to Movie Recommender System"

movies = pickle.load(open("movies.pkl","rb"))
similarity = pickle.load(open("similarity.pkl","rb"))

@app.route("/recommend/<movie>")
def recommend(movie):

    movie_index = movies[
        movies["title"] == movie
    ].index[0]

    distances = similarity[movie_index]

    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x:x[1]
    )[1:11]

    recommendations = []

    for i in movie_list:
        recommendations.append(
            movies.iloc[i[0]].title
        )

    return jsonify(recommendations)

if __name__ == "__main__":
    app.run()
