# -*- coding: utf-8 -*-
"""Movie_Rec_Sys

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aL2bM8opXnjjRDR8hAY_PjjHKjXqJN_e
"""

import pandas as pd
import pickle

#Data Processing Script
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

print(movies.shape)
print(credits.shape)

#Merge Datasets
movies = movies.merge(
    credits,
    on="title"
)

#Extract Genres, Cast, Director
import ast

def convert(text):

    result = []

    for item in ast.literal_eval(text):
        result.append(item["name"])

    return result

movies["genres"] = movies["genres"].apply(convert)

movies["keywords"] = movies["keywords"].apply(convert)

#Top 3 Cast Members
def get_cast(text):

    result = []

    counter = 0

    for item in ast.literal_eval(text):

        if counter != 3:
            result.append(item["name"])
            counter += 1
        else:
            break

    return result

movies["cast"] = movies["cast"].apply(get_cast)

#Director
def get_director(text):

    for item in ast.literal_eval(text):

        if item["job"] == "Director":
            return item["name"]

    return ""

movies["crew"] = movies["crew"].apply(get_director)

#Create Tags
movies["overview"] = movies["overview"].fillna("")

movies["overview"] = movies["overview"].apply(
    lambda x: x.split()
)

movies["tags"] = (
      movies["overview"]
    + movies["genres"]
    + movies["keywords"]
    + movies["cast"]
)

movies = movies[
    ["movie_id", "title", "tags"]
]

#Convert Tags to Text
movies["tags"] = movies["tags"].apply(
    lambda x: " ".join(x)
)

movies.to_csv(
    "processed_movies.csv",
    index=False
)