# -*- coding: utf-8 -*-
"""Test_Model_Movie_Rec_Sys

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cGJaEqhBVbHIvaNrJ9pPtd4PNfab7ZPF
"""

import pickle

#Test Recommendations

movies = pickle.load(
    open("movies.pkl", "rb")
)

similarity = pickle.load(
    open("similarity.pkl", "rb")
)


def recommend(movie):

    movie_index = movies[
        movies["title"] == movie
    ].index[0]

    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    for i in movies_list:
        print(
            movies.iloc[i[0]].title
        )


recommend("Avatar")