# -*- coding: utf-8 -*-
"""Train_Model_Movie_Rec_Sys

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1WJ8vLX4WRze0ffd4cxop3CssyZ0DjB
"""

import pandas as pd
import pickle

#Create Similarity Matrix

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

movies = pd.read_csv("processed_movies.csv")

cv = CountVectorizer(
    max_features=5000,
    stop_words="english"
)

vectors = cv.fit_transform(
    movies["tags"]
).toarray()

similarity = cosine_similarity(vectors)

pickle.dump(
    movies,
    open("movies.pkl", "wb")
)

pickle.dump(
    similarity,
    open("similarity.pkl", "wb")
)

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

movies = pd.read_csv("processed_movies.csv")

cv = CountVectorizer(
    max_features=5000,
    stop_words="english"
)

vectors = cv.fit_transform(
    movies["tags"]
).toarray()

similarity = cosine_similarity(vectors)

pickle.dump(
    movies,
    open("movies.pkl", "wb")
)

pickle.dump(
    similarity,
    open("similarity.pkl", "wb")
)

print("Model Trained Successfully")